YgoLocals/Controllers/DeckController.cs
namespace YgoLocals.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using YgoLocals.Core.EntityServices.Deck;
    using YgoLocals.Data.Entities;
    using YgoLocals.Models.Deck;

    public class DeckController : BaseController
    {
        private readonly IDeckService _deckService;
        private readonly UserManager<User> _userManager;

        public DeckController(IDeckService deckService, UserManager<User> userManager)
        {
            _deckService = deckService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userDecks = await _deckService.GetAllByUserAsync(_userManager.GetUserId(User));

            return View(userDecks);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DeckInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var deckId = await _deckService.CreateAsync(_userManager.GetUserId(User), input.Name);

            return RedirectToAction(nameof(Index));
        }
    }
}

YgoLocals/Controllers/MatchController.cs
namespace YgoLocals.Controllers
{
    using System;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using YgoLocals.Core.EntityServices.Match;
    using YgoLocals.Data.Entities;
    using YgoLocals.Models.Match;

    public class MatchController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly IMatchService _matchService;

        public MatchController(UserManager<User> userManager, IMatchService matchService)
        {
            _userManager = userManager;
            _matchService = matchService;
        }

        public async Task<IActionResult> Index()
        {
            var baseMatchViewModel = new BaseMatchViewModel()
            {
                AvaiableToJoin = await _matchService.GetAllAvaiable(),
                UserActiveMatches = await _matchService.GetAllActiveByUser(_userManager.GetUserId(User)),
            };

            return View(baseMatchViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create()
        {
            var matchId = await _matchService.CreateAsync(_userManager.GetUserId(User));

            return RedirectToAction(nameof(Details), new { id = matchId });
        }

        public async Task<IActionResult> Details(string id)
        {
            var match = await _matchService.GetByIdAsync(id);
            return View(match);
        }

        [HttpPost]
        public async Task<IActionResult> Join(string id)
        {
            await _matchService.JoinAsync(id, _userManager.GetUserId(User));
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> End(EndMatchInputModel input)
        {
            await _matchService.EndAsync(input.MatchId, input.WinnerId);
            return RedirectToAction(nameof(Details), new { id = input.MatchId });
        }

        public async Task<IActionResult> PastMatches()
        {
            var matches = await _matchService.GetAllPastByUser(_userManager.GetUserId(User));
            return View(matches);
        }
    }
}

YgoLocals/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YgoLocals</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YgoLocals.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">YgoLocals</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_NavMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - YgoLocals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@*    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
*@

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


@*    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YgoLocals/Views/Shared/_NavMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using YgoLocals.Data.Entities
@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Deck" asp-action="Index">Decks</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Deck" asp-action="Create">Create</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Tournament" asp-action="Create">Create Tournament</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Tournament" asp-action="Index">Tournaments</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="Index">Matches</a>
    </li>
}
else
{
    @*    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>*@
}